* ascii-paint

ascii-paint is a clone of the original ascii-paint by and . The project was
abandoned in 2011 and was forked by Ben Porter (see the [[https://bitbucket.org/bpio/ascii-paint/overview][bitbucket page]], which
was then subsequently abandoned in 2013.

I decided to clone the original repository because Google Code is shutting
down, and because the original code doesn't compile or link with the latest
version of libtcod.

* building

The build process is not straightforward because of the dependency on libtcod
(which, unfortunately, has almost no build process). You have to download and
build libtcod first, and then copy the libraries to the ascii-paint directory
for cmake to find.

   * Download version 1.5.1 of libtcod from [[http://roguecentral.org/doryen/libtcod/download/][here]]. Newer version of the library
     might work, I don't know yet.
   * Extract it somewhere, switch to the directory and build libtcod using the
     appropriate makefile (for most people, this means executing =make -f makefiles/makefile-linux64=).
   * Some .so files will be generated. Copy them to the ascii-paint root
     directory (next to the source files).
   * Build ascii-paint. In the root directory of ascii-paint: =mkdir build; cd build; cmake ..; make=. The binary will be generated in
     the "build" directory.
